/**
 * Agent preset — a portable, **secret-free** snapshot of a bot's shareable
 * configuration.
 *
 * `botmux preset export <bot>` writes one of these so a teammate's agent can
 * self-configure a *matching* bot WITHOUT ever copying credentials. It carries
 * only the parts that are safe to share — which CLI/model to use, the team-level
 * role persona, and the one-line capability label — plus an embedded Chinese
 * guide telling the receiving agent how to apply it.
 *
 * It deliberately omits everything identity- or deployment-specific:
 * larkAppId / larkAppSecret / allowedUsers / allowedChatGroups / oncallChats /
 * workingDir. Those must be supplied by each bot's own owner. The safety
 * guarantee lives in `buildPreset`, which copies an explicit allow-list of
 * fields and NEVER spreads its input, so a caller passing a full bot config
 * (secrets and all) still produces a clean preset.
 */
import { z } from 'zod';

/**
 * On-disk preset format version. Doubles as a format discriminator: a file
 * whose `botmuxPreset` !== PRESET_VERSION is rejected by `loadPreset`. Bump
 * only on a breaking change to the shape below.
 */
export const PRESET_VERSION = 1;

/**
 * A secret-free, shareable bot preset. Field order here matches the serialized
 * JSON (see `buildPreset`): marker first, identity-free config in the middle,
 * human guide last.
 */
export interface AgentPreset {
  /** Format marker + version. Always equal to {@link PRESET_VERSION}. */
  botmuxPreset: number;
  /** CLI adapter id the source bot uses (e.g. 'claude-code', 'aiden'). */
  cliId: string;
  /** Model override, if the source bot set one. */
  model?: string;
  /** Team-level role markdown (the persona injected into the CLI). */
  teamRole?: string;
  /** One-line capability label used in the collaboration roster. */
  capability?: string;
  /** Human-facing name of the source bot — for display / default filename. */
  sourceName?: string;
  /** Chinese guide telling the *receiving* agent how to apply this preset. */
  guide: string;
}

/**
 * Input accepted by {@link buildPreset}. The named fields are the allow-list;
 * the index signature exists so callers can pass a full bot config (which also
 * carries secrets like larkAppSecret) without a type error — those extra keys
 * are simply never read.
 */
export interface BuildPresetInput {
  cliId: string;
  model?: string | null;
  teamRole?: string | null;
  capability?: string | null;
  sourceName?: string | null;
  /** Tolerate (and ignore) any extra fields, e.g. a full bot config's secrets. */
  [extra: string]: unknown;
}

/**
 * Guide embedded in every exported preset, addressed to the AI agent that will
 * apply it on the receiving side. Kept in the file so it travels with the data.
 */
export const PRESET_GUIDE = [
  'This file is a botmux Agent preset generated by `botmux preset export`.',
  'It contains configuration that is safe to share: CLI adapter (cliId), model, team persona (teamRole), and capability label.',
  '',
  'It contains no credentials or deployment information: no larkAppId, larkAppSecret, allowedUsers, allowedChatGroups, or workingDir.',
  'This file alone cannot sign in or impersonate the original bot. That is intentional.',
  '',
  'If you are an AI agent, follow these steps to apply this preset to the user\'s own botmux bot:',
  '1. Have the user run `botmux setup` with their own Feishu/Lark app credentials. They must provide larkAppId, larkAppSecret, and allowedUsers.',
  '   Never copy credentials from this file or another person.',
  '   When creating a bot, do not copy BOTMUX_OWNER_OPEN_ID injected into the current session or any ou_ value from the source bot. An open_id belongs only to the app that issued it.',
  '   Use a full email address, mobile number, or on_ union_id so setup can resolve and validate the owner under the target app.',
  '2. In setup, select this preset\'s cliId and model when present.',
  '3. Set the bot\'s team-level role content to teamRole and its capability label to capability.',
  '4. Run `botmux restart` after configuration.',
  '',
  'Each bot must use independent credentials (AppID, secret, or token) provided by its owner. Never copy another person\'s credentials.',
].join('\n');

/**
 * Build a preset by copying an explicit allow-list of fields. Never spreads
 * `input`, so any secret-bearing extra keys on it are dropped by construction.
 * Empty / null / undefined optional fields are omitted entirely.
 */
export function buildPreset(input: BuildPresetInput): AgentPreset {
  const preset = {
    botmuxPreset: PRESET_VERSION,
    cliId: input.cliId,
  } as AgentPreset;

  if (input.model) preset.model = input.model;
  if (input.teamRole) preset.teamRole = input.teamRole;
  if (input.capability) preset.capability = input.capability;
  if (input.sourceName) preset.sourceName = input.sourceName;

  // Guide last so it reads naturally at the bottom of the JSON file.
  preset.guide = PRESET_GUIDE;
  return preset;
}

/** Serialize a preset to pretty JSON with a trailing newline (POSIX-friendly). */
export function serializePreset(preset: AgentPreset): string {
  return JSON.stringify(preset, null, 2) + '\n';
}

/**
 * Slugify a string into a safe filename component: keep Unicode letters / digits
 * / `_` / `.` / `-`, replace every other run with a single `-`, then trim
 * leading/trailing separators. Returns '' if nothing usable remains (e.g. the
 * input was only spaces or slashes). CJK names are preserved (they're \p{L}).
 */
export function slugifyForFilename(raw: string): string {
  return raw
    .trim()
    .replace(/[^\p{L}\p{N}_.-]+/gu, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^[.\-]+|[.\-]+$/g, '');
}

/**
 * Derive the default preset filename (no directory). Prefers the bot's human
 * name, falls back to its larkAppId, and ALWAYS slugifies so the path stays
 * valid/stable even when `name` carries spaces, slashes, etc. Never uses the
 * `botmux-<n>` process name. Final 'bot' fallback guards the degenerate case
 * where both name and appId slug to empty.
 */
export function presetFilename(sourceName: string | undefined, appId: string): string {
  const base = slugifyForFilename(sourceName ?? '') || slugifyForFilename(appId) || 'bot';
  return `${base}.botmux-preset.json`;
}

const presetSchema = z.object({
  botmuxPreset: z.literal(PRESET_VERSION),
  cliId: z.string().min(1),
  model: z.string().optional(),
  teamRole: z.string().optional(),
  capability: z.string().optional(),
  sourceName: z.string().optional(),
  guide: z.string(),
});

/**
 * Parse + validate a preset JSON string. Throws a friendly error on malformed
 * JSON or on a wrong/missing version (kept for tests and future "preset apply"
 * tooling). Unknown extra keys are stripped, so a future minor extension stays
 * readable by older code as long as the version still matches.
 */
export function loadPreset(raw: string): AgentPreset {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch (err: any) {
    throw new Error(`不是合法的 JSON: ${err?.message ?? String(err)}`);
  }

  const result = presetSchema.safeParse(parsed);
  if (!result.success) {
    const detail = result.error.issues
      .map(i => `${i.path.join('.') || '(root)'}: ${i.message}`)
      .join('; ');
    throw new Error(`不是合法的 botmux 预设 (需要 botmuxPreset=${PRESET_VERSION}): ${detail}`);
  }
  return result.data;
}
